# Generated by Django 2.1.1 on 2018-09-26 10:15

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_choice', models.CharField(choices=[('char', 'Character'), ('txt', 'Text'), ('int', 'Integer'), ('flo', 'Float'), ('dat', 'Date'), ('datt', 'DateTime'), ('img', 'Image'), ('fle', 'File')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('quality_degree', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(blank=True, default=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(blank=True, max_length=100000, null=True)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('int_field', models.IntegerField(blank=True, null=True)),
                ('big_int_field', models.BigIntegerField(blank=True, null=True)),
                ('float_field', models.FloatField(blank=True, null=True)),
                ('date_field', models.DateField(default=django.utils.timezone.now)),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('file_field', models.FileField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Field')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('inherit_unit_price', models.BooleanField(default=False)),
                ('tax', models.IntegerField(blank=True, default=0)),
                ('inherit_tax', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('inherit_discount', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(blank=True, default=True)),
                ('inherit_availability', models.BooleanField(default=True)),
                ('is_tax_included', models.BooleanField(blank=True, default=False)),
                ('inherit_tax_included', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.Reseller'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='product.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='product.Unit'),
        ),
        migrations.AddField(
            model_name='field',
            name='type_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Type'),
        ),
    ]
