# Generated by Django 2.1.1 on 2018-09-26 10:14

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('trashed', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text="Used to Create Post's URL", max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('archived', 'Archived'), ('published', 'Published'), ('hidden', 'Hidden')], default='draft', max_length=20)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text="It's Article Publish Date")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_publish_date', models.DateTimeField(blank=True, help_text='Start Date of a Publication', null=True)),
                ('end_publish_date', models.DateTimeField(blank=True, help_text='End Date of a Publication', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish_date',),
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a Category Name', max_length=150)),
                ('slug', models.SlugField(help_text='Category URL', max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=8000, null=True)),
                ('description', models.CharField(blank=True, max_length=8000, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='PageCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Enter the page name that want hitcounter on it. ', max_length=150)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
